CONTAINER Osolidchamfer
{
	NAME Osolidchamfer;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		LONG SOLIDCHAMFER_EDGESELECTION	{CYCLE{ SC_LIVE; SC_TAG; SC_ALL; SC_PHONG;}}
		LINK SOLIDCHAMFER_TAGLINK {ACCEPT { Tedgeselection; } }
		REAL SOLIDCHAMFER_RADIUS	   { UNIT METER; MIN 0.0; }
		LONG SOLIDCHAMFER_SUBDIVISION	 { MIN 0; MAX 6; }
	}
}
